### PR TITLE
D646042: Fix defect where batches were not being returned correctly

### PR DESCRIPTION
**Pull request by jonny-mccoubrey**
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=646042

### CODE REVIEW

**Review by dermot-hardy — CHANGES_REQUESTED** [review]
This would work, but it would be more efficient if the sorting was done after the filtering, so that there are less elements to sort.

**Comment by jonny-mccoubrey** [comment]
> This would work, but it would be more efficient if the sorting was done after the filtering, so that there are less elements to sort.

@dermot-hardy the issue described in [D646042](https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=646042) will not be fixed if sorting is done after filtering.

**Comment by dermot-hardy** [comment]
I didn't say after the limit.  I said after the filters.

**Review by dermot-hardy — CHANGES_REQUESTED** [review]
This is just the same.  It is still before the filters.

**Comment by jonny-mccoubrey** [comment]
> I didn't say after the limit. I said after the filters.



> This is just the same. It is still before the filters.

Understand what you mean now - updated accordingly

**Review by dermot-hardy — APPROVED** [review]

**Pull request merged**
