### PR TITLE
D453042: Adding in check for file already exists

### PR DESCRIPTION
**Pull request by tbroadbent22**
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=453042

### CODE REVIEW

**Review by dermot-hardy — APPROVED** [review]

**Review by dermot-hardy — CHANGES_REQUESTED** [review]
On reflection there is a multi-threading issue here.  If two health checks are run at the same time then one of them might fail.

**Comment by tbroadbent22** [comment]
We could use a timestamp as part of the file name to give uniqueness, if there are 2 threads then theoretically they should be atleast a milisecond apart resulting in a different timestamp and a new file if creation is possible, although this could lead to a build up of files on the server

**Comment by dermot-hardy** [comment]
How about you use the thread id instead of a timestamp?

**Comment by tbroadbent22** [comment]
Yeah can do that

**Review by dermot-hardy — CHANGES_REQUESTED** [review]
What is the flow here?  If `DiskAccessHealthIndicatorWithTimeout` is a singleton then presumably there wasn't an issue here at all (because of the single thread executor).  If it is not then it seems unlikely that this will be unique.

**Comment by tbroadbent22** [comment]
I'm not sure what you mean. I followed the same pattern as DiskSpaceHealthIndicatorWithTimeout

**Comment by dermot-hardy** [comment]
How many times does a `DiskAccessHealthIndicatorWithTimeout` object get constructed during the process lifetime?  Is it just a single time during startup, or several times during startup, or every time a `/status` or `/healthcheck` call is made?

**Comment by tbroadbent22** [comment]
From what I can see it gets constructed twice during setup

**Comment by dermot-hardy** [comment]
Ok.  If both are constructed on the same thread then adding the thread id hasn't resolved the issue.  If both are guaranteed to be constructed on different threads then the code would be ok, but this is too subtle.  It needs to be fixed in a way that it clearly works.

**Comment by tbroadbent22** [comment]
in that case a UUID sounds the most logical option -> UUID.randomUUID();

**Comment by dermot-hardy** [comment]
Using a UUID would have the same issue that you had with timestamp (i.e. it could lead to orphaned files).

**Review by frankmccarry — APPROVED** [review]
Looks good. Thanks.

**Pull request merged**
