### PR TITLE
SCMOD-7274: False postive comment updated for Path Manipulation

### PR DESCRIPTION
**Pull request by thilagasanthosh**
https://portal.digitalsafe.net/browse/SCMOD-7274

### CODE REVIEW

**Review by dermot-hardy — CHANGES_REQUESTED** [review]
All the comments are:

> The value of basePath is retrieved using properties or env variables.

But looking through the Fortify Path Manipulation issues I can't see any issues being reported relating to the base path at all.  So far as I can see they are all relating to either the `tenantId` or the `batchId`.

**Comment by dermot-hardy** [comment]
I'm closing this PR and deleting the branch because I don't think there's anything worth salvaging in it.

**Comment by dermot-hardy** [comment]
Start a new branch.  On it try solution 2 from your guidance document for both tenant id and batch id.

**Comment by thilagasanthosh** [comment]
@dermot-hardy ,
The BatchId class has the pattern matching for input batchId value.
https://github.com/CAFDataProcessing/staging-service/blob/60f055fd81263fdecdb339f0883215d7663ef0c5/staging-service-shared/src/main/java/com/github/cafdataprocessing/services/staging/BatchId.java#L24

The same for TenantId
https://github.com/CAFDataProcessing/staging-service/blob/60f055fd81263fdecdb339f0883215d7663ef0c5/staging-service-shared/src/main/java/com/github/cafdataprocessing/services/staging/TenantId.java#L24

In that case, the Path Manipulation violations seem to be false positive from fortify.
Please confirm

**Comment by dermot-hardy** [comment]
The Fortify recommendation is to use positive checks - i.e. limit what characters are allowed - rather than limiting which characters are disallowed.  I am OK with these checks, but if moving to a set of allowed characters fixes the Fortify issues then we should do that.

**Pull request closed without merging**
